version: '3.8'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:31.0.2
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=10G
    volumes:
      - /mnt/host_storage/nextcloud/config:/config 
      - /mnt/host_storage/nextcloud/data:/data 
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - nextcloud-frontend
      - nextcloud-backend
    depends_on:
      - mariadb

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - /mnt/host_storage/nextcloud/nc_metadata:/var/lib/mysql
    restart: unless-stopped
    networks:
      - nextcloud-backend

  cloudflared-nextcloud:
    image: cloudflare/cloudflared:2025.2.1
    container_name: cloudflared
    restart: always
    command: >
      tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      - nextcloud-frontend

  collabora:
    image: collabora/code:24.04.13.2.1
    container_name: collabora
    restart: always
    environment:
      - password=${COLLABORA_PASSWORD}
      - username=admin
      - domain=doc.silkandcypress.us
      - server_name=office.silkandcypress.us
    networks:
      - nextcloud-frontend

networks:
  nextcloud-frontend:
    external: true

  nextcloud-backend:
    external: true